import type { z } from "zod";
import {
  traitMapConstructMappingSchema,
  traitMapEvidenceFindingSchema,
  traitMapEvidenceSourceSchema,
} from "@/features/nuang-code/trait-map-data-center-v2";

type EvidenceSource = z.infer<typeof traitMapEvidenceSourceSchema>;
type EvidenceFinding = z.infer<typeof traitMapEvidenceFindingSchema>;
type ConstructMapping = z.infer<typeof traitMapConstructMappingSchema>;

export const traitMapFoundationEvidenceSourcesV2 = [
  {
    sourceId: "SRC-TEST-STANDARDS-2014",
    title: "Standards for Educational and Psychological Testing",
    authors: [
      "American Educational Research Association",
      "American Psychological Association",
      "National Council on Measurement in Education",
    ],
    year: 2014,
    researchStream: "measurement_and_validity",
    sourceType: "standard",
    peerReviewStatus: "official_standard",
    url: "https://www.testingstandards.net/",
    languages: ["English"],
    countries: ["not_applicable"],
    populationSummary:
      "교육·심리검사의 개발, 타당성, 공정성, 채점, 해석과 사용을 위한 전문 표준",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "method_only",
      riskOfBias: "not_applicable",
      culturalFit: "method_only",
      replication: "not_applicable",
    },
  },
  {
    sourceId: "SRC-ITC-2017",
    title: "ITC Guidelines for Translating and Adapting Tests, Second Edition",
    authors: ["International Test Commission"],
    year: 2017,
    researchStream: "language_and_culture",
    sourceType: "standard",
    peerReviewStatus: "official_standard",
    url: "https://www.intestcom.org/files/guideline_test_adaptation_2ed.pdf",
    languages: ["English", "Korean_translation_available"],
    countries: ["international"],
    populationSummary:
      "검사를 다른 언어와 문화 환경에 옮길 때 필요한 사전 조건, 개발, 경험적 확인, 시행, 해석과 문서화 지침",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "method_only",
      riskOfBias: "not_applicable",
      culturalFit: "cross_cultural",
      replication: "not_applicable",
    },
  },
  {
    sourceId: "SRC-BFI2-2017",
    title:
      "The Next Big Five Inventory (BFI-2): Developing and Assessing a Hierarchical Model With 15 Facets",
    authors: ["Christopher J. Soto", "Oliver P. John"],
    year: 2017,
    researchStream: "personality_facets",
    sourceType: "measurement_study",
    peerReviewStatus: "peer_reviewed",
    doi: "10.1037/pspp0000096",
    url: "https://escholarship.org/uc/item/16x6n05t",
    languages: ["English"],
    countries: ["United States"],
    populationSummary:
      "세 연구와 독립 검증 표본에서 5개 domain과 15개 facet의 위계적 성격 측정을 개발·평가",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "partial",
      riskOfBias: "some_concerns",
      culturalFit: "non_korean",
      replication: "multiple_samples",
    },
  },
  {
    sourceId: "SRC-BFAS-2007",
    title: "Between Facets and Domains: 10 Aspects of the Big Five",
    authors: [
      "Colin G. DeYoung",
      "Lena C. Quilty",
      "Jordan B. Peterson",
    ],
    year: 2007,
    researchStream: "personality_facets",
    sourceType: "measurement_study",
    peerReviewStatus: "peer_reviewed",
    doi: "10.1037/0022-3514.93.5.880",
    url: "https://pubmed.ncbi.nlm.nih.gov/17983306/",
    languages: ["English"],
    countries: ["Canada"],
    populationSummary:
      "Big Five domain과 더 구체적인 facet 사이에서 10개 aspect 구조를 평가",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "partial",
      riskOfBias: "some_concerns",
      culturalFit: "non_korean",
      replication: "multiple_samples",
    },
  },
  {
    sourceId: "SRC-IPC-2013",
    title:
      "Unifying the Aspects of the Big Five, the Interpersonal Circumplex, and Trait Affiliation",
    authors: [
      "Colin G. DeYoung",
      "Yanna J. Weisberg",
      "Lena C. Quilty",
      "Jordan B. Peterson",
    ],
    year: 2013,
    researchStream: "personality_facets",
    sourceType: "measurement_study",
    peerReviewStatus: "peer_reviewed",
    doi: "10.1111/jopy.12020",
    url: "https://doi.org/10.1111/jopy.12020",
    languages: ["English"],
    countries: ["Canada"],
    populationSummary:
      "세 표본에서 Big Five aspect와 대인 행동 구조의 구분과 연결을 검토",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "partial",
      riskOfBias: "some_concerns",
      culturalFit: "non_korean",
      replication: "multiple_samples",
    },
  },
  {
    sourceId: "SRC-EXTRAVERSION-PA-2015",
    title: "Clarifying the Relation Between Extraversion and Positive Affect",
    authors: ["Luke D. Smillie", "Colin G. DeYoung", "Philip J. Hall"],
    year: 2015,
    researchStream: "personality_facets",
    sourceType: "peer_reviewed_study",
    peerReviewStatus: "peer_reviewed",
    doi: "10.1111/jopy.12138",
    url: "https://doi.org/10.1111/jopy.12138",
    languages: ["English"],
    countries: ["Australia", "Canada"],
    populationSummary:
      "외향성·주도성·열정과 긍정 정서의 관계를 구분해 검토",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "partial",
      riskOfBias: "some_concerns",
      culturalFit: "non_korean",
      replication: "single_sample",
    },
  },
  {
    sourceId: "SRC-OPENNESS-INTELLECT-2009",
    title: "Intellect as Distinct From Openness",
    authors: [
      "Colin G. DeYoung",
      "Naftali A. Shamosh",
      "Adam E. Green",
      "Todd S. Braver",
      "Jeremy R. Gray",
    ],
    year: 2009,
    researchStream: "personality_facets",
    sourceType: "measurement_study",
    peerReviewStatus: "peer_reviewed",
    doi: "10.1037/a0016615",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2805551/",
    languages: ["English"],
    countries: ["United States"],
    populationSummary:
      "Openness와 Intellect의 관련성과 구분, 인지 능력과의 관계를 검토",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "partial",
      riskOfBias: "some_concerns",
      culturalFit: "non_korean",
      replication: "multiple_samples",
    },
  },
  {
    sourceId: "SRC-STATE-DISTRIBUTION-2001",
    title:
      "Toward a Structure- and Process-Integrated View of Personality: Traits as Density Distributions of States",
    authors: ["William Fleeson"],
    year: 2001,
    researchStream: "person_situation_process",
    sourceType: "experience_sampling_study",
    peerReviewStatus: "peer_reviewed",
    doi: "10.1037/0022-3514.80.6.1011",
    url: "https://doi.org/10.1037/0022-3514.80.6.1011",
    languages: ["English"],
    countries: ["United States"],
    populationSummary:
      "세 경험표집 연구에서 일상 성향 상태의 개인 내 변산과 개인 간 중심 경향을 함께 검토",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "partial",
      riskOfBias: "some_concerns",
      culturalFit: "non_korean",
      replication: "multiple_samples",
    },
  },
  {
    sourceId: "SRC-WHOLE-TRAIT-2015",
    title: "Whole Trait Theory",
    authors: ["William Fleeson", "Eranda Jayawickreme"],
    year: 2015,
    researchStream: "person_situation_process",
    sourceType: "peer_reviewed_study",
    peerReviewStatus: "peer_reviewed",
    doi: "10.1016/j.jrp.2014.10.009",
    url: "https://pubmed.ncbi.nlm.nih.gov/26097268/",
    languages: ["English"],
    countries: ["United States"],
    populationSummary:
      "성향의 기술적 분포와 행동을 설명하는 사회인지 과정을 구분하고 연결한 통합 이론",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "method_only",
      riskOfBias: "not_applicable",
      culturalFit: "method_only",
      replication: "not_applicable",
    },
  },
  {
    sourceId: "SRC-STATE-MEASUREMENT-2020",
    title:
      "Assessing Personality States: What to Consider When Constructing Personality State Measures",
    authors: ["Kai T. Horstmann", "Matthias Ziegler"],
    year: 2020,
    researchStream: "measurement_and_validity",
    sourceType: "peer_reviewed_study",
    peerReviewStatus: "peer_reviewed",
    doi: "10.1002/per.2266",
    url: "https://doi.org/10.1002/per.2266",
    languages: ["English"],
    countries: ["Germany"],
    populationSummary:
      "성격 상태 측정의 목적과 문항·회상 기간·상황·행동 표현 설계 고려사항을 정리",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "method_only",
      riskOfBias: "not_applicable",
      culturalFit: "method_only",
      replication: "not_applicable",
    },
  },
  {
    sourceId: "SRC-DIAMONDS-2014",
    title:
      "The Situational Eight DIAMONDS: A Taxonomy of Major Dimensions of Situation Characteristics",
    authors: [
      "John F. Rauthmann",
      "Ry Ry Sherman",
      "David C. Funder",
    ],
    year: 2014,
    researchStream: "person_situation_process",
    sourceType: "measurement_study",
    peerReviewStatus: "peer_reviewed",
    doi: "10.1037/a0037250",
    url: "https://pubmed.ncbi.nlm.nih.gov/25133715/",
    languages: ["English"],
    countries: ["United States", "Germany"],
    populationSummary:
      "여러 연구에서 주요 상황 특성의 분류와 행동 예측에서의 활용을 검토",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "method_only",
      riskOfBias: "some_concerns",
      culturalFit: "cross_cultural",
      replication: "multiple_samples",
    },
  },
  {
    sourceId: "SRC-KOREA-SITUATION-2024",
    title: "Cultural Validation of Situational DIAMONDS in South Korea",
    authors: ["source_authors_pending_bibliographic_verification"],
    year: 2024,
    researchStream: "language_and_culture",
    sourceType: "cross_cultural_study",
    peerReviewStatus: "peer_reviewed",
    doi: "10.1016/j.paid.2024.112616",
    url: "https://doi.org/10.1016/j.paid.2024.112616",
    languages: ["Korean"],
    countries: ["South Korea"],
    populationSummary:
      "한국의 25~39세 성인 445명을 대상으로 상황 특성 분류의 문화적 적용 가능성을 검토",
    sampleSize: 445,
    screeningStatus: "included",
    quality: {
      directness: "method_only",
      riskOfBias: "some_concerns",
      culturalFit: "korean_direct",
      replication: "single_sample",
    },
  },
  {
    sourceId: "SRC-EMOTION-PROCESS-1998",
    title: "Antecedent- and Response-Focused Emotion Regulation",
    authors: ["James J. Gross"],
    year: 1998,
    researchStream: "emotion_stress_recovery",
    sourceType: "peer_reviewed_study",
    peerReviewStatus: "peer_reviewed",
    doi: "10.1037/0022-3514.74.1.224",
    url: "https://pubmed.ncbi.nlm.nih.gov/9457784/",
    languages: ["English"],
    countries: ["United States"],
    populationSummary:
      "감정 조절 시점에 따라 경험·표현·생리 반응을 구분해 검토",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "indirect",
      riskOfBias: "some_concerns",
      culturalFit: "non_korean",
      replication: "single_sample",
    },
  },
  {
    sourceId: "SRC-DYAD-2010",
    title: "Predicting Relationship and Life Satisfaction From Personality",
    authors: [
      "Portia S. Dyrenforth",
      "Deborah A. Kashy",
      "M. Brent Donnellan",
      "Richard E. Lucas",
    ],
    year: 2010,
    researchStream: "romantic_relationships",
    sourceType: "peer_reviewed_study",
    peerReviewStatus: "peer_reviewed",
    doi: "10.1037/a0020385",
    url: "https://pubmed.ncbi.nlm.nih.gov/20718544/",
    languages: ["multiple"],
    countries: ["Australia", "Germany", "United Kingdom"],
    populationSummary:
      "세 나라의 대규모 부부 표본에서 actor·partner·similarity 효과를 분리해 관계와 삶의 만족을 검토",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "partial",
      riskOfBias: "some_concerns",
      culturalFit: "cross_cultural",
      replication: "multiple_samples",
    },
  },
  {
    sourceId: "SRC-CONTENT-VALIDITY-2018",
    title:
      "COSMIN Methodology for Evaluating the Content Validity of Patient-Reported Outcome Measures: A Delphi Study",
    authors: [
      "Lidwine B. Mokkink",
      "Caroline B. Terwee",
      "Donald L. Patrick",
      "Jordi Alonso",
      "Paul W. Stratford",
      "Dirk L. Knol",
      "Lex M. Bouter",
      "Henrica C. W. de Vet",
    ],
    year: 2018,
    researchStream: "measurement_and_validity",
    sourceType: "measurement_study",
    peerReviewStatus: "peer_reviewed",
    doi: "10.1007/s11136-018-1829-0",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5891557/",
    languages: ["English"],
    countries: ["international"],
    populationSummary:
      "국제 전문가 Delphi와 파일럿을 통해 관련성·포괄성·이해 가능성의 내용타당도 기준을 합의",
    sampleSize: null,
    screeningStatus: "included",
    quality: {
      directness: "method_only",
      riskOfBias: "some_concerns",
      culturalFit: "method_only",
      replication: "not_applicable",
    },
  },
] as const satisfies readonly EvidenceSource[];

export const traitMapFoundationEvidenceFindingsV2 = [
  {
    findingId: "FND-TEST-STANDARDS-VALIDITY-USE",
    sourceId: "SRC-TEST-STANDARDS-2014",
    constructRefs: ["score_interpretation", "intended_use", "validity"],
    contexts: ["general"],
    direction: "method_only",
    evidenceGrade: "A",
    populationSummary: "교육·심리검사의 개발자와 사용자",
    resultSummary:
      "타당성 근거는 검사 이름 전체가 아니라 특정 점수 해석과 사용을 지지하도록 축적해야 한다.",
    limitations: [
      "뉴앙 5축이나 특정 claim을 직접 검증하는 경험 연구가 아니다.",
    ],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-EVIDENCE-LEDGER.part1.v0.1"],
  },
  {
    findingId: "FND-ITC-CULTURAL-ADAPTATION",
    sourceId: "SRC-ITC-2017",
    constructRefs: ["test_adaptation", "cultural_equivalence"],
    contexts: ["general"],
    direction: "method_only",
    evidenceGrade: "A",
    populationSummary: "다언어·다문화 검사 개발과 사용",
    resultSummary:
      "번역만으로 등가성을 가정하지 않고 목표 언어·문화에서 경험적으로 확인하고 문서화해야 한다.",
    limitations: ["뉴앙 한국어 문항의 문화 적합성을 직접 확인한 자료가 아니다."],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-EVIDENCE-LEDGER.part1.v0.1"],
  },
  {
    findingId: "FND-BFI2-HIERARCHICAL-FACETS",
    sourceId: "SRC-BFI2-2017",
    constructRefs: ["broad_domains", "facets", "hierarchical_measurement"],
    contexts: ["general"],
    direction: "supports",
    evidenceGrade: "B",
    populationSummary: "미국 영어권 성인 개발·검증 표본",
    resultSummary:
      "넓은 성격 영역 아래 더 구체적인 facet을 구분해 측정하는 위계 구조가 독립 표본에서 평가됐다.",
    limitations: [
      "BFI-2의 domain과 facet을 뉴앙 축·facet과 동일시할 수 없다.",
      "영어권 표본 결과가 뉴앙 한국어 문항의 타당성을 대신하지 않는다.",
    ],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-EVIDENCE-LEDGER.part1.v0.1"],
  },
  {
    findingId: "FND-BFAS-DOMAIN-ASPECT-DISTINCTION",
    sourceId: "SRC-BFAS-2007",
    constructRefs: ["broad_domains", "aspects"],
    contexts: ["general"],
    direction: "supports",
    evidenceGrade: "B",
    populationSummary: "캐나다 성격 측정 표본",
    resultSummary:
      "넓은 Big Five 영역과 관련되지만 구분되는 두 aspect 층을 모델링할 수 있었다.",
    limitations: [
      "뉴앙의 모든 축이 정확히 두 facet으로 구성된다는 근거가 아니다.",
    ],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-EVIDENCE-LEDGER.part1.v0.1"],
  },
  {
    findingId: "FND-IPC-INTERPERSONAL-DISTINCTIONS",
    sourceId: "SRC-IPC-2013",
    constructRefs: [
      "assertiveness",
      "enthusiasm",
      "compassion",
      "politeness",
    ],
    contexts: ["general", "friend", "partner", "work"],
    direction: "supports",
    evidenceGrade: "B",
    populationSummary: "세 성격·대인 행동 표본",
    resultSummary:
      "먼저 표현하고 관여하는 경향과 상대에게 향하는 친화·배려 관련 경향은 대인 구조에서 구분된다.",
    limitations: [
      "뉴앙 SE-AI 또는 RO-EC를 직접 측정한 연구가 아니다.",
      "뉴앙 A를 Agreeableness나 Compassion 전체로 바꿀 수 없다.",
    ],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-EVIDENCE-LEDGER.part1.v0.1"],
  },
  {
    findingId: "FND-EXTRAVERSION-NOT-SIMPLE-HAPPINESS",
    sourceId: "SRC-EXTRAVERSION-PA-2015",
    constructRefs: ["extraversion", "positive_affect", "activation"],
    contexts: ["general"],
    direction: "qualifies",
    evidenceGrade: "C",
    populationSummary: "외향성과 긍정 정서 관련 표본",
    resultSummary:
      "외향성과 긍정 정서의 관계를 단순한 행복감보다 활성 수준과 함께 구분할 필요가 있다.",
    limitations: ["뉴앙 SE-RE의 직접 타당화 자료가 아니다."],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-EVIDENCE-LEDGER.part1.v0.1"],
  },
  {
    findingId: "FND-OPENNESS-INTELLECT-DISTINCTION",
    sourceId: "SRC-OPENNESS-INTELLECT-2009",
    constructRefs: ["openness", "intellect", "cognitive_ability"],
    contexts: ["general", "work"],
    direction: "supports",
    evidenceGrade: "B",
    populationSummary: "미국 성격·인지 측정 표본",
    resultSummary:
      "Openness와 Intellect는 관련되지만 구분되며, Intellect와 인지 능력의 관련도 동일한 구성개념을 뜻하지 않는다.",
    limitations: [
      "뉴앙 OE의 세 facet 구조와 한국어 문항은 별도로 검증해야 한다.",
    ],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-EVIDENCE-LEDGER.part1.v0.1"],
  },
  {
    findingId: "FND-STATE-DISTRIBUTION-STABILITY-VARIABILITY",
    sourceId: "SRC-STATE-DISTRIBUTION-2001",
    constructRefs: ["personality_states", "within_person_variability"],
    contexts: ["general", "family", "friend", "partner", "work"],
    direction: "supports",
    evidenceGrade: "B",
    populationSummary: "2~3주 동안 반복 보고한 미국 참여자",
    resultSummary:
      "개인은 일상에서 다양한 성향 상태를 보이면서도 상태 분포의 중심 경향에서는 안정적인 개인차를 보일 수 있다.",
    limitations: [
      "뉴앙 다섯 축의 변산 크기나 ENAKQ 고유 행동을 직접 제시하지 않는다.",
    ],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-EVIDENCE-LEDGER.part1.v0.1"],
  },
  {
    findingId: "FND-WHOLE-TRAIT-DESCRIPTION-EXPLANATION",
    sourceId: "SRC-WHOLE-TRAIT-2015",
    constructRefs: ["trait_description", "explanatory_process"],
    contexts: ["general", "family", "friend", "partner", "work"],
    direction: "method_only",
    evidenceGrade: "B",
    populationSummary: "성격 상태와 사회인지 과정에 관한 통합 이론",
    resultSummary:
      "성향의 기술적 분포와 그 행동을 설명하는 과정을 구분하면서 연결해야 한다.",
    limitations: [
      "뉴앙의 처음 생각·실제 반응 코드나 조합 효과를 직접 검증하지 않는다.",
    ],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-EVIDENCE-LEDGER.part1.v0.1"],
  },
  {
    findingId: "FND-STATE-MEASUREMENT-DESIGN",
    sourceId: "SRC-STATE-MEASUREMENT-2020",
    constructRefs: ["personality_state_measurement", "item_design"],
    contexts: ["general"],
    direction: "method_only",
    evidenceGrade: "B",
    populationSummary: "성격 상태 측정 도구 개발 방법",
    resultSummary:
      "성격 상태 문항은 측정 목적, 시간 범위, 상황과 행동 표현을 명확히 구분해 설계해야 한다.",
    limitations: ["뉴앙 문항의 내용타당도나 구조를 직접 평가한 자료가 아니다."],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-EVIDENCE-LEDGER.part1.v0.1"],
  },
  {
    findingId: "FND-DIAMONDS-SITUATION-CHARACTERISTICS",
    sourceId: "SRC-DIAMONDS-2014",
    constructRefs: ["situation_characteristics", "behavior_prediction"],
    contexts: ["general", "family", "friend", "partner", "work"],
    direction: "method_only",
    evidenceGrade: "B",
    populationSummary: "여러 상황 특성 개발·검증 표본",
    resultSummary:
      "사람의 성향과 별도로 상황의 주요 특성을 분류하고 행동 예측에 함께 사용할 수 있다.",
    limitations: [
      "DIAMONDS 차원을 뉴앙 5W1H 상황 ID와 동일시하지 않는다.",
    ],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["NUANG-TRAIT-MAP-SCENARIO-ONTOLOGY.v2"],
  },
  {
    findingId: "FND-KOREA-SITUATION-CULTURAL-FIT",
    sourceId: "SRC-KOREA-SITUATION-2024",
    constructRefs: ["situation_characteristics", "korean_cultural_fit"],
    contexts: ["general", "family", "friend", "partner", "work"],
    direction: "qualifies",
    evidenceGrade: "C",
    populationSummary: "한국 25~39세 성인 445명",
    resultSummary:
      "한국 표본에서도 상황 특성의 문화적 적용 가능성을 별도로 확인해야 한다는 지역 근거를 제공한다.",
    limitations: [
      "뉴앙 상황 라벨과 72개 canonical 상황을 직접 검증한 자료가 아니다.",
      "서지 저자 정보는 원문 기준으로 추가 확인이 필요하다.",
    ],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-EVIDENCE-LEDGER.part2.v0.1"],
  },
  {
    findingId: "FND-EMOTION-EXPERIENCE-EXPRESSION-DISTINCTION",
    sourceId: "SRC-EMOTION-PROCESS-1998",
    constructRefs: ["emotion_experience", "emotion_expression", "regulation"],
    contexts: ["general", "family", "friend", "partner", "work"],
    direction: "qualifies",
    evidenceGrade: "C",
    populationSummary: "감정 조절 시점의 실험 연구",
    resultSummary:
      "감정 경험과 외부 표현, 생리 반응은 같은 것으로 취급하지 않고 조절 시점과 함께 구분할 필요가 있다.",
    limitations: [
      "뉴앙 Q/C나 개인의 감정조절 능력을 직접 측정한 자료가 아니다.",
    ],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-EVIDENCE-LEDGER.part1.v0.1"],
  },
  {
    findingId: "FND-DYAD-SIMILARITY-BOUNDARY",
    sourceId: "SRC-DYAD-2010",
    constructRefs: [
      "actor_effect",
      "partner_effect",
      "personality_similarity",
      "relationship_satisfaction",
    ],
    contexts: ["partner"],
    direction: "qualifies",
    evidenceGrade: "B",
    populationSummary: "호주·독일·영국의 대규모 부부 표본",
    resultSummary:
      "성향 유사성은 actor와 partner 효과를 통제한 뒤 관계·삶 만족의 작은 추가 변량만 설명했다.",
    limitations: [
      "모든 관계 유형과 뉴앙 코드에 같은 효과 크기를 적용할 수 없다.",
      "같은 코드나 다른 코드를 궁합 점수로 바꾸는 근거가 아니다.",
    ],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-EVIDENCE-LEDGER.part1.v0.1"],
  },
  {
    findingId: "FND-COSMIN-CONTENT-VALIDITY",
    sourceId: "SRC-CONTENT-VALIDITY-2018",
    constructRefs: [
      "content_relevance",
      "content_comprehensiveness",
      "content_comprehensibility",
    ],
    contexts: ["general"],
    direction: "method_only",
    evidenceGrade: "A",
    populationSummary: "측정·내용타당도 국제 전문가 Delphi",
    resultSummary:
      "내용타당도는 관련성·포괄성·이해 가능성을 구분하고 목표 사용자의 평가를 포함해 판단해야 한다.",
    limitations: [
      "환자보고결과 도구 중심 방법론이므로 뉴앙에 맞는 탐침과 판정 규칙을 별도로 명시해야 한다.",
    ],
    extractedBy: "nuang-research-v2",
    verifiedBy: ["ENAKQ-GATE-C-COGNITIVE-CONTENT-VALIDITY.v0.1"],
  },
] as const satisfies readonly EvidenceFinding[];

export const traitMapFoundationConstructMappingsV2 = [
  {
    mappingId: "MAP-BFI2-EXTRAVERSION-SE",
    externalConstruct: "BFI-2 Extraversion",
    nuangTarget: { kind: "axis", ref: "SE" },
    relation: "partial",
    rationale:
      "교류 활력과 먼저 표현하기의 구조적 참고가 되지만 뉴앙 SE의 측정 범위와 문항은 별도다.",
    prohibitedEquivalences: [
      "BFI-2 Extraversion 점수를 뉴앙 E/I로 변환하지 않는다.",
      "E를 행복·인기·사교 능력으로 해석하지 않는다.",
    ],
    evidenceFindingRefs: [
      "FND-BFI2-HIERARCHICAL-FACETS",
      "FND-EXTRAVERSION-NOT-SIMPLE-HAPPINESS",
    ],
    status: "research_candidate",
  },
  {
    mappingId: "MAP-BFI2-OPEN-MINDEDNESS-OE",
    externalConstruct: "BFI-2 Open-Mindedness and Openness/Intellect",
    nuangTarget: { kind: "axis", ref: "OE" },
    relation: "partial",
    rationale:
      "미적 경험·상상·지적 탐구의 구분에 참고하지만 뉴앙 OE 3-facet 구조는 별도 검증 대상이다.",
    prohibitedEquivalences: [
      "BFI-2 Open-Mindedness 점수를 뉴앙 R/N으로 변환하지 않는다.",
      "N을 지능·창의성·예술 능력으로 해석하지 않는다.",
    ],
    evidenceFindingRefs: [
      "FND-BFI2-HIERARCHICAL-FACETS",
      "FND-OPENNESS-INTELLECT-DISTINCTION",
    ],
    status: "research_candidate",
  },
  {
    mappingId: "MAP-BIG-FIVE-AGREEABLENESS-RO",
    externalConstruct: "Big Five Agreeableness and interpersonal affiliation",
    nuangTarget: { kind: "axis", ref: "RO" },
    relation: "adjacent",
    rationale:
      "관계 속 관심 방향을 설명하는 간접 참고이지만 뉴앙 RO-EC는 Agreeableness 전체보다 좁다.",
    prohibitedEquivalences: [
      "A를 착함·공감 능력·예절·협력 능력으로 해석하지 않는다.",
      "G를 차가움이나 낮은 Agreeableness로 해석하지 않는다.",
    ],
    evidenceFindingRefs: ["FND-IPC-INTERPERSONAL-DISTINCTIONS"],
    status: "research_candidate",
  },
  {
    mappingId: "MAP-BIG-FIVE-CONSCIENTIOUSNESS-SM",
    externalConstruct: "Big Five Conscientiousness aspects and facets",
    nuangTarget: { kind: "axis", ref: "SM" },
    relation: "adjacent",
    rationale:
      "실행·지속과 질서·구조를 구분하는 구조적 참고지만 뉴앙 K/M은 성실성 전체가 아니다.",
    prohibitedEquivalences: [
      "K를 책임감·도덕성·성과로 해석하지 않는다.",
      "M을 게으름이나 무책임으로 해석하지 않는다.",
    ],
    evidenceFindingRefs: [
      "FND-BFI2-HIERARCHICAL-FACETS",
      "FND-BFAS-DOMAIN-ASPECT-DISTINCTION",
    ],
    status: "research_candidate",
  },
  {
    mappingId: "MAP-BIG-FIVE-NEGATIVE-EMOTIONALITY-ER",
    externalConstruct: "Big Five Negative Emotionality",
    nuangTarget: { kind: "axis", ref: "ER" },
    relation: "partial",
    rationale:
      "감정 동요와 걱정·주저를 구분하는 참고이지만 뉴앙 Q/C는 정신건강이나 회복력을 측정하지 않는다.",
    prohibitedEquivalences: [
      "Q를 불안장애·우울·취약함으로 해석하지 않는다.",
      "C를 회복력·감정조절 능력·정신건강으로 해석하지 않는다.",
    ],
    evidenceFindingRefs: [
      "FND-BFI2-HIERARCHICAL-FACETS",
      "FND-EMOTION-EXPERIENCE-EXPRESSION-DISTINCTION",
    ],
    status: "research_candidate",
  },
  {
    mappingId: "MAP-ASSERTIVENESS-SE-AI",
    externalConstruct: "Assertiveness and interpersonal agency",
    nuangTarget: { kind: "facet", ref: "SE-AI" },
    relation: "partial",
    rationale:
      "필요한 말을 먼저 꺼내는 경향과 인접하지만 권력·지배·리더십 능력은 측정 범위에서 제외한다.",
    prohibitedEquivalences: [
      "SE-AI를 지배성·리더십·설득 능력으로 해석하지 않는다.",
    ],
    evidenceFindingRefs: ["FND-IPC-INTERPERSONAL-DISTINCTIONS"],
    status: "research_candidate",
  },
  {
    mappingId: "MAP-OPENNESS-OE-AE-CI",
    externalConstruct: "Openness",
    nuangTarget: { kind: "facet", ref: "OE-AE" },
    relation: "partial",
    rationale:
      "미적 경험 관심의 구성개념 참고이며 상상 확장·지적 탐구와 같은 것으로 합치지 않는다.",
    prohibitedEquivalences: [
      "OE-AE를 예술 능력이나 미적 판단의 정확성으로 해석하지 않는다.",
    ],
    evidenceFindingRefs: ["FND-OPENNESS-INTELLECT-DISTINCTION"],
    status: "research_candidate",
  },
  {
    mappingId: "MAP-INTELLECT-OE-IE",
    externalConstruct: "Intellect",
    nuangTarget: { kind: "facet", ref: "OE-IE" },
    relation: "partial",
    rationale:
      "원리·배경·다른 설명을 더 탐구하는 경향의 참고이며 지능과 동일하지 않다.",
    prohibitedEquivalences: [
      "OE-IE를 지능·학업성취·이해 속도로 해석하지 않는다.",
    ],
    evidenceFindingRefs: ["FND-OPENNESS-INTELLECT-DISTINCTION"],
    status: "research_candidate",
  },
  {
    mappingId: "MAP-EMOTION-REGULATION-ER",
    externalConstruct: "Emotion regulation process",
    nuangTarget: { kind: "axis", ref: "ER" },
    relation: "non_equivalent",
    rationale:
      "감정 경험과 외부 표현을 구분해야 한다는 경계 근거로만 사용한다.",
    prohibitedEquivalences: [
      "ER 점수에서 개인의 감정조절 전략이나 능력을 추정하지 않는다.",
    ],
    evidenceFindingRefs: [
      "FND-EMOTION-EXPERIENCE-EXPRESSION-DISTINCTION",
    ],
    status: "research_candidate",
  },
] as const satisfies readonly ConstructMapping[];

export const traitMapFoundationEvidenceV2 = {
  sources: traitMapFoundationEvidenceSourcesV2,
  findings: traitMapFoundationEvidenceFindingsV2,
  mappings: traitMapFoundationConstructMappingsV2,
} as const;
